# Generated by Django 4.1.5 on 2023-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
